export const championsData = [
  {
    id: "Aatrox",
    name: "Aatrox",
    spells: ["AatroxQ", "AatroxW", "AatroxE", "AatroxR"],
  },
  { id: "Ahri", name: "Ahri", spells: ["AhriQ", "AhriW", "AhriE", "AhriR"] },
  {
    id: "Akali",
    name: "Akali",
    spells: ["AkaliQ", "AkaliW", "AkaliE", "AkaliR"],
  },
  {
    id: "Akshan",
    name: "Akshan",
    spells: ["AkshanQ", "AkshanW", "AkshanE", "AkshanR"],
  },
  {
    id: "Alistar",
    name: "Alistar",
    spells: ["Pulverize", "Headbutt", "AlistarE", "FerociousHowl"],
  },
  {
    id: "Amumu",
    name: "Amumu",
    spells: ["BandageToss", "AuraofDespair", "Tantrum", "CurseoftheSadMummy"],
  },
  {
    id: "Anivia",
    name: "Anivia",
    spells: ["FlashFrost", "Crystallize", "Frostbite", "GlacialStorm"],
  },
  {
    id: "Annie",
    name: "Annie",
    spells: ["AnnieQ", "AnnieW", "AnnieE", "AnnieR"],
  },
  {
    id: "Aphelios",
    name: "Aphelios",
    spells: [
      "ApheliosQ_ClientTooltipWrapper",
      "ApheliosW",
      "ApheliosE_ClientTooltipWrapper",
      "ApheliosR",
    ],
  },
  {
    id: "Ashe",
    name: "Ashe",
    spells: ["AsheQ", "Volley", "AsheSpiritOfTheHawk", "EnchantedCrystalArrow"],
  },
  {
    id: "AurelionSol",
    name: "Aurelion Sol",
    spells: ["AurelionSolQ", "AurelionSolW", "AurelionSolE", "AurelionSolR"],
  },
  {
    id: "Azir",
    name: "Azir",
    spells: ["AzirQWrapper", "AzirW", "AzirEWrapper", "AzirR"],
  },
  { id: "Bard", name: "Bard", spells: ["BardQ", "BardW", "BardE", "BardR"] },
  {
    id: "Belveth",
    name: "Bel'Veth",
    spells: ["BelvethQ", "BelvethW", "BelvethE", "BelvethR"],
  },
  {
    id: "Blitzcrank",
    name: "Blitzcrank",
    spells: ["RocketGrab", "Overdrive", "PowerFist", "StaticField"],
  },
  {
    id: "Brand",
    name: "Brand",
    spells: ["BrandQ", "BrandW", "BrandE", "BrandR"],
  },
  {
    id: "Braum",
    name: "Braum",
    spells: ["BraumQ", "BraumW", "BraumE", "BraumRWrapper"],
  },
  {
    id: "Caitlyn",
    name: "Caitlyn",
    spells: ["CaitlynQ", "CaitlynW", "CaitlynE", "CaitlynR"],
  },
  {
    id: "Camille",
    name: "Camille",
    spells: ["CamilleQ", "CamilleW", "CamilleE", "CamilleR"],
  },
  {
    id: "Cassiopeia",
    name: "Cassiopeia",
    spells: ["CassiopeiaQ", "CassiopeiaW", "CassiopeiaE", "CassiopeiaR"],
  },
  {
    id: "Chogath",
    name: "Cho'Gath",
    spells: ["Rupture", "FeralScream", "VorpalSpikes", "Feast"],
  },
  {
    id: "Corki",
    name: "Corki",
    spells: ["PhosphorusBomb", "CarpetBomb", "GGun", "MissileBarrage"],
  },
  {
    id: "Darius",
    name: "Darius",
    spells: [
      "DariusCleave",
      "DariusNoxianTacticsONH",
      "DariusAxeGrabCone",
      "DariusExecute",
    ],
  },
  {
    id: "Diana",
    name: "Diana",
    spells: ["DianaQ", "DianaOrbs", "DianaTeleport", "DianaR"],
  },
  {
    id: "Draven",
    name: "Draven",
    spells: ["DravenSpinning", "DravenFury", "DravenDoubleShot", "DravenRCast"],
  },
  {
    id: "DrMundo",
    name: "Dr. Mundo",
    spells: ["DrMundoQ", "DrMundoW", "DrMundoE", "DrMundoR"],
  },
  { id: "Ekko", name: "Ekko", spells: ["EkkoQ", "EkkoW", "EkkoE", "EkkoR"] },
  {
    id: "Elise",
    name: "Elise",
    spells: ["EliseHumanQ", "EliseHumanW", "EliseHumanE", "EliseR"],
  },
  {
    id: "Evelynn",
    name: "Evelynn",
    spells: ["EvelynnQ", "EvelynnW", "EvelynnE", "EvelynnR"],
  },
  {
    id: "Ezreal",
    name: "Ezreal",
    spells: ["EzrealQ", "EzrealW", "EzrealE", "EzrealR"],
  },
  {
    id: "Fiddlesticks",
    name: "Fiddlesticks",
    spells: [
      "FiddleSticksQ",
      "FiddleSticksW",
      "FiddleSticksE",
      "FiddleSticksR",
    ],
  },
  {
    id: "Fiora",
    name: "Fiora",
    spells: ["FioraQ", "FioraW", "FioraE", "FioraR"],
  },
  { id: "Fizz", name: "Fizz", spells: ["FizzQ", "FizzW", "FizzE", "FizzR"] },
  {
    id: "Galio",
    name: "Galio",
    spells: ["GalioQ", "GalioW", "GalioE", "GalioR"],
  },
  {
    id: "Gangplank",
    name: "Gangplank",
    spells: ["GangplankQWrapper", "GangplankW", "GangplankE", "GangplankR"],
  },
  {
    id: "Garen",
    name: "Garen",
    spells: ["GarenQ", "GarenW", "GarenE", "GarenR"],
  },
  { id: "Gnar", name: "Gnar", spells: ["GnarQ", "GnarW", "GnarE", "GnarR"] },
  {
    id: "Gragas",
    name: "Gragas",
    spells: ["GragasQ", "GragasW", "GragasE", "GragasR"],
  },
  {
    id: "Graves",
    name: "Graves",
    spells: [
      "GravesQLineSpell",
      "GravesSmokeGrenade",
      "GravesMove",
      "GravesChargeShot",
    ],
  },
  { id: "Gwen", name: "Gwen", spells: ["GwenQ", "GwenW", "GwenE", "GwenR"] },
  {
    id: "Hecarim",
    name: "Hecarim",
    spells: ["HecarimRapidSlash", "HecarimW", "HecarimRamp", "HecarimUlt"],
  },
  {
    id: "Heimerdinger",
    name: "Heimerdinger",
    spells: [
      "HeimerdingerQ",
      "HeimerdingerW",
      "HeimerdingerE",
      "HeimerdingerR",
    ],
  },
  {
    id: "Illaoi",
    name: "Illaoi",
    spells: ["IllaoiQ", "IllaoiW", "IllaoiE", "IllaoiR"],
  },
  {
    id: "Irelia",
    name: "Irelia",
    spells: ["IreliaQ", "IreliaW", "IreliaE", "IreliaR"],
  },
  {
    id: "Ivern",
    name: "Ivern",
    spells: ["IvernQ", "IvernW", "IvernE", "IvernR"],
  },
  {
    id: "Janna",
    name: "Janna",
    spells: ["HowlingGale", "SowTheWind", "EyeOfTheStorm", "ReapTheWhirlwind"],
  },
  {
    id: "JarvanIV",
    name: "Jarvan IV",
    spells: [
      "JarvanIVDragonStrike",
      "JarvanIVGoldenAegis",
      "JarvanIVDemacianStandard",
      "JarvanIVCataclysm",
    ],
  },
  {
    id: "Jax",
    name: "Jax",
    spells: [
      "JaxLeapStrike",
      "JaxEmpowerTwo",
      "JaxCounterStrike",
      "JaxRApexForm",
    ],
  },
  {
    id: "Jayce",
    name: "Jayce",
    spells: [
      "JayceToTheSkies",
      "JayceStaticField",
      "JayceThunderingBlow",
      "JayceStanceHtG",
    ],
  },
  { id: "Jhin", name: "Jhin", spells: ["JhinQ", "JhinW", "JhinE", "JhinR"] },
  { id: "Jinx", name: "Jinx", spells: ["JinxQ", "JinxW", "JinxE", "JinxR"] },
  {
    id: "Kaisa",
    name: "Kai'Sa",
    spells: ["KaisaQ", "KaisaW", "KaisaE", "KaisaR"],
  },
  {
    id: "Kalista",
    name: "Kalista",
    spells: [
      "KalistaMysticShot",
      "KalistaW",
      "KalistaExpungeWrapper",
      "KalistaRx",
    ],
  },
  {
    id: "Karma",
    name: "Karma",
    spells: ["KarmaQ", "KarmaSpiritBind", "KarmaSolKimShield", "KarmaMantra"],
  },
  {
    id: "Karthus",
    name: "Karthus",
    spells: [
      "KarthusLayWasteA1",
      "KarthusWallOfPain",
      "KarthusDefile",
      "KarthusFallenOne",
    ],
  },
  {
    id: "Kassadin",
    name: "Kassadin",
    spells: ["NullLance", "NetherBlade", "ForcePulse", "RiftWalk"],
  },
  {
    id: "Katarina",
    name: "Katarina",
    spells: ["KatarinaQ", "KatarinaW", "KatarinaEWrapper", "KatarinaR"],
  },
  {
    id: "Kayle",
    name: "Kayle",
    spells: ["KayleQ", "KayleW", "KayleE", "KayleR"],
  },
  { id: "Kayn", name: "Kayn", spells: ["KaynQ", "KaynW", "KaynE", "KaynR"] },
  {
    id: "Kennen",
    name: "Kennen",
    spells: [
      "KennenShurikenHurlMissile1",
      "KennenBringTheLight",
      "KennenLightningRush",
      "KennenShurikenStorm",
    ],
  },
  {
    id: "Khazix",
    name: "Kha'Zix",
    spells: ["KhazixQ", "KhazixW", "KhazixE", "KhazixR"],
  },
  {
    id: "Kindred",
    name: "Kindred",
    spells: ["KindredQ", "KindredW", "KindredEWrapper", "KindredR"],
  },
  { id: "Kled", name: "Kled", spells: ["KledQ", "KledW", "KledE", "KledR"] },
  {
    id: "KogMaw",
    name: "Kog'Maw",
    spells: [
      "KogMawQ",
      "KogMawBioArcaneBarrage",
      "KogMawVoidOoze",
      "KogMawLivingArtillery",
    ],
  },
  {
    id: "KSante",
    name: "K'Sante",
    spells: ["KSanteQ", "KSanteW", "KSanteE", "KSanteR"],
  },
  {
    id: "Leblanc",
    name: "LeBlanc",
    spells: ["LeblancQ", "LeblancW", "LeblancE", "LeblancR"],
  },
  {
    id: "LeeSin",
    name: "Lee Sin",
    spells: [
      "BlindMonkQOne",
      "BlindMonkWOne",
      "BlindMonkEOne",
      "BlindMonkRKick",
    ],
  },
  {
    id: "Leona",
    name: "Leona",
    spells: [
      "LeonaShieldOfDaybreak",
      "LeonaSolarBarrier",
      "LeonaZenithBlade",
      "LeonaSolarFlare",
    ],
  },
  {
    id: "Lillia",
    name: "Lillia",
    spells: ["LilliaQ", "LilliaW", "LilliaE", "LilliaR"],
  },
  {
    id: "Lissandra",
    name: "Lissandra",
    spells: ["LissandraQ", "LissandraW", "LissandraE", "LissandraR"],
  },
  {
    id: "Lucian",
    name: "Lucian",
    spells: ["LucianQ", "LucianW", "LucianE", "LucianR"],
  },
  { id: "Lulu", name: "Lulu", spells: ["LuluQ", "LuluW", "LuluE", "LuluR"] },
  {
    id: "Lux",
    name: "Lux",
    spells: [
      "LuxLightBinding",
      "LuxPrismaticWave",
      "LuxLightStrikeKugel",
      "LuxR",
    ],
  },
  {
    id: "Malphite",
    name: "Malphite",
    spells: ["SeismicShard", "Obduracy", "Landslide", "UFSlash"],
  },
  {
    id: "Malzahar",
    name: "Malzahar",
    spells: ["MalzaharQ", "MalzaharW", "MalzaharE", "MalzaharR"],
  },
  {
    id: "Maokai",
    name: "Maokai",
    spells: ["MaokaiQ", "MaokaiW", "MaokaiE", "MaokaiR"],
  },
  {
    id: "MasterYi",
    name: "Master Yi",
    spells: ["AlphaStrike", "Meditate", "WujuStyle", "Highlander"],
  },
  {
    id: "MissFortune",
    name: "Miss Fortune",
    spells: [
      "MissFortuneRicochetShot",
      "MissFortuneViciousStrikes",
      "MissFortuneScattershot",
      "MissFortuneBulletTime",
    ],
  },
  {
    id: "MonkeyKing",
    name: "Wukong",
    spells: [
      "MonkeyKingDoubleAttack",
      "MonkeyKingDecoy",
      "MonkeyKingNimbus",
      "MonkeyKingSpinToWin",
    ],
  },
  {
    id: "Mordekaiser",
    name: "Mordekaiser",
    spells: ["MordekaiserQ", "MordekaiserW", "MordekaiserE", "MordekaiserR"],
  },
  {
    id: "Morgana",
    name: "Morgana",
    spells: ["MorganaQ", "MorganaW", "MorganaE", "MorganaR"],
  },
  { id: "Nami", name: "Nami", spells: ["NamiQ", "NamiW", "NamiE", "NamiR"] },
  {
    id: "Nasus",
    name: "Nasus",
    spells: ["NasusQ", "NasusW", "NasusE", "NasusR"],
  },
  {
    id: "Nautilus",
    name: "Nautilus",
    spells: [
      "NautilusAnchorDrag",
      "NautilusPiercingGaze",
      "NautilusSplashZone",
      "NautilusGrandLine",
    ],
  },
  {
    id: "Neeko",
    name: "Neeko",
    spells: ["NeekoQ", "NeekoW", "NeekoE", "NeekoR"],
  },
  {
    id: "Nidalee",
    name: "Nidalee",
    spells: ["JavelinToss", "Bushwhack", "PrimalSurge", "AspectOfTheCougar"],
  },
  {
    id: "Nilah",
    name: "Nilah",
    spells: ["NilahQ", "NilahW", "NilahE", "NilahR"],
  },
  {
    id: "Nocturne",
    name: "Nocturne",
    spells: [
      "NocturneDuskbringer",
      "NocturneShroudofDarkness",
      "NocturneUnspeakableHorror",
      "NocturneParanoia",
    ],
  },
  {
    id: "Nunu",
    name: "Nunu & Willump",
    spells: ["NunuQ", "NunuW", "NunuE", "NunuR"],
  },
  {
    id: "Olaf",
    name: "Olaf",
    spells: [
      "OlafAxeThrowCast",
      "OlafFrenziedStrikes",
      "OlafRecklessStrike",
      "OlafRagnarok",
    ],
  },
  {
    id: "Orianna",
    name: "Orianna",
    spells: [
      "OrianaIzunaCommand",
      "OrianaDissonanceCommand",
      "OrianaRedactCommand",
      "OrianaDetonateCommand",
    ],
  },
  { id: "Ornn", name: "Ornn", spells: ["OrnnQ", "OrnnW", "OrnnE", "OrnnR"] },
  {
    id: "Pantheon",
    name: "Pantheon",
    spells: ["PantheonQ", "PantheonW", "PantheonE", "PantheonR"],
  },
  {
    id: "Poppy",
    name: "Poppy",
    spells: ["PoppyQ", "PoppyW", "PoppyE", "PoppyR"],
  },
  { id: "Pyke", name: "Pyke", spells: ["PykeQ", "PykeW", "PykeE", "PykeR"] },
  {
    id: "Qiyana",
    name: "Qiyana",
    spells: ["QiyanaQ", "QiyanaW", "QiyanaE", "QiyanaR"],
  },
  {
    id: "Quinn",
    name: "Quinn",
    spells: ["QuinnQ", "QuinnW", "QuinnE", "QuinnR"],
  },
  {
    id: "Rakan",
    name: "Rakan",
    spells: ["RakanQ", "RakanW", "RakanE", "RakanR"],
  },
  {
    id: "Rammus",
    name: "Rammus",
    spells: ["PowerBall", "DefensiveBallCurl", "PuncturingTaunt", "Tremors2"],
  },
  {
    id: "RekSai",
    name: "Rek'Sai",
    spells: ["RekSaiQ", "RekSaiW", "RekSaiE", "RekSaiRWrapper"],
  },
  {
    id: "Rell",
    name: "Rell",
    spells: ["RellQ", "RellW_Dismount", "RellE", "RellR"],
  },
  {
    id: "Renata",
    name: "Renata Glasc",
    spells: ["RenataQ", "RenataW", "RenataE", "RenataR"],
  },
  {
    id: "Renekton",
    name: "Renekton",
    spells: [
      "RenektonCleave",
      "RenektonPreExecute",
      "RenektonSliceAndDice",
      "RenektonReignOfTheTyrant",
    ],
  },
  {
    id: "Rengar",
    name: "Rengar",
    spells: ["RengarQ", "RengarW", "RengarE", "RengarR"],
  },
  {
    id: "Riven",
    name: "Riven",
    spells: [
      "RivenTriCleave",
      "RivenMartyr",
      "RivenFeint",
      "RivenFengShuiEngine",
    ],
  },
  {
    id: "Rumble",
    name: "Rumble",
    spells: [
      "RumbleFlameThrower",
      "RumbleShield",
      "RumbleGrenade",
      "RumbleCarpetBomb",
    ],
  },
  {
    id: "Ryze",
    name: "Ryze",
    spells: ["RyzeQWrapper", "RyzeW", "RyzeE", "RyzeR"],
  },
  {
    id: "Samira",
    name: "Samira",
    spells: ["SamiraQ", "SamiraW", "SamiraE", "SamiraR"],
  },
  {
    id: "Sejuani",
    name: "Sejuani",
    spells: ["SejuaniQ", "SejuaniW", "SejuaniE", "SejuaniR"],
  },
  {
    id: "Senna",
    name: "Senna",
    spells: ["SennaQ", "SennaW", "SennaE", "SennaR"],
  },
  {
    id: "Seraphine",
    name: "Seraphine",
    spells: ["SeraphineQ", "SeraphineW", "SeraphineE", "SeraphineR"],
  },
  { id: "Sett", name: "Sett", spells: ["SettQ", "SettW", "SettE", "SettR"] },
  {
    id: "Shaco",
    name: "Shaco",
    spells: ["Deceive", "JackInTheBox", "TwoShivPoison", "HallucinateFull"],
  },
  { id: "Shen", name: "Shen", spells: ["ShenQ", "ShenW", "ShenE", "ShenR"] },
  {
    id: "Shyvana",
    name: "Shyvana",
    spells: [
      "ShyvanaDoubleAttack",
      "ShyvanaImmolationAura",
      "ShyvanaFireball",
      "ShyvanaTransformCast",
    ],
  },
  {
    id: "Singed",
    name: "Singed",
    spells: ["PoisonTrail", "MegaAdhesive", "Fling", "InsanityPotion"],
  },
  { id: "Sion", name: "Sion", spells: ["SionQ", "SionW", "SionE", "SionR"] },
  {
    id: "Sivir",
    name: "Sivir",
    spells: ["SivirQ", "SivirW", "SivirE", "SivirR"],
  },
  {
    id: "Skarner",
    name: "Skarner",
    spells: [
      "SkarnerVirulentSlash",
      "SkarnerExoskeleton",
      "SkarnerFracture",
      "SkarnerImpale",
    ],
  },
  { id: "Sona", name: "Sona", spells: ["SonaQ", "SonaW", "SonaE", "SonaR"] },
  {
    id: "Soraka",
    name: "Soraka",
    spells: ["SorakaQ", "SorakaW", "SorakaE", "SorakaR"],
  },
  {
    id: "Swain",
    name: "Swain",
    spells: ["SwainQ", "SwainW", "SwainE", "SwainR"],
  },
  {
    id: "Sylas",
    name: "Sylas",
    spells: ["SylasQ", "SylasW", "SylasE", "SylasR"],
  },
  {
    id: "Syndra",
    name: "Syndra",
    spells: ["SyndraQ", "SyndraW", "SyndraE", "SyndraR"],
  },
  {
    id: "TahmKench",
    name: "Tahm Kench",
    spells: ["TahmKenchQ", "TahmKenchW", "TahmKenchE", "TahmKenchRWrapper"],
  },
  {
    id: "Taliyah",
    name: "Taliyah",
    spells: ["TaliyahQ", "TaliyahWVC", "TaliyahE", "TaliyahR"],
  },
  {
    id: "Talon",
    name: "Talon",
    spells: ["TalonQ", "TalonW", "TalonE", "TalonR"],
  },
  {
    id: "Taric",
    name: "Taric",
    spells: ["TaricQ", "TaricW", "TaricE", "TaricR"],
  },
  {
    id: "Teemo",
    name: "Teemo",
    spells: ["BlindingDart", "MoveQuick", "ToxicShot", "TeemoRCast"],
  },
  {
    id: "Thresh",
    name: "Thresh",
    spells: ["ThreshQ", "ThreshW", "ThreshE", "ThreshRPenta"],
  },
  {
    id: "Tristana",
    name: "Tristana",
    spells: ["TristanaQ", "TristanaW", "TristanaE", "TristanaR"],
  },
  {
    id: "Trundle",
    name: "Trundle",
    spells: [
      "TrundleTrollSmash",
      "trundledesecrate",
      "TrundleCircle",
      "TrundlePain",
    ],
  },
  {
    id: "Tryndamere",
    name: "Tryndamere",
    spells: ["TryndamereQ", "TryndamereW", "TryndamereE", "UndyingRage"],
  },
  {
    id: "TwistedFate",
    name: "Twisted Fate",
    spells: ["WildCards", "PickACard", "CardmasterStack", "Destiny"],
  },
  {
    id: "Twitch",
    name: "Twitch",
    spells: [
      "TwitchHideInShadows",
      "TwitchVenomCask",
      "TwitchExpunge",
      "TwitchFullAutomatic",
    ],
  },
  { id: "Udyr", name: "Udyr", spells: ["UdyrQ", "UdyrW", "UdyrE", "UdyrR"] },
  {
    id: "Urgot",
    name: "Urgot",
    spells: ["UrgotQ", "UrgotW", "UrgotE", "UrgotR"],
  },
  {
    id: "Varus",
    name: "Varus",
    spells: ["VarusQ", "VarusW", "VarusE", "VarusR"],
  },
  {
    id: "Vayne",
    name: "Vayne",
    spells: [
      "VayneTumble",
      "VayneSilveredBolts",
      "VayneCondemn",
      "VayneInquisition",
    ],
  },
  {
    id: "Veigar",
    name: "Veigar",
    spells: [
      "VeigarBalefulStrike",
      "VeigarDarkMatter",
      "VeigarEventHorizon",
      "VeigarR",
    ],
  },
  {
    id: "Velkoz",
    name: "Vel'Koz",
    spells: ["VelkozQ", "VelkozW", "VelkozE", "VelkozR"],
  },
  { id: "Vex", name: "Vex", spells: ["VexQ", "VexW", "VexE", "VexR"] },
  { id: "Vi", name: "Vi", spells: ["ViQ", "ViW", "ViE", "ViR"] },
  {
    id: "Viego",
    name: "Viego",
    spells: ["ViegoQ", "ViegoW", "ViegoE", "ViegoR"],
  },
  {
    id: "Viktor",
    name: "Viktor",
    spells: [
      "ViktorPowerTransfer",
      "ViktorGravitonField",
      "ViktorDeathRay",
      "ViktorChaosStorm",
    ],
  },
  {
    id: "Vladimir",
    name: "Vladimir",
    spells: [
      "VladimirQ",
      "VladimirSanguinePool",
      "VladimirE",
      "VladimirHemoplague",
    ],
  },
  {
    id: "Volibear",
    name: "Volibear",
    spells: ["VolibearQ", "VolibearW", "VolibearE", "VolibearR"],
  },
  {
    id: "Warwick",
    name: "Warwick",
    spells: ["WarwickQ", "WarwickW", "WarwickE", "WarwickR"],
  },
  {
    id: "Xayah",
    name: "Xayah",
    spells: ["XayahQ", "XayahW", "XayahE", "XayahR"],
  },
  {
    id: "Xerath",
    name: "Xerath",
    spells: [
      "XerathArcanopulseChargeUp",
      "XerathArcaneBarrage2",
      "XerathMageSpear",
      "XerathLocusOfPower2",
    ],
  },
  {
    id: "XinZhao",
    name: "Xin Zhao",
    spells: ["XinZhaoQ", "XinZhaoW", "XinZhaoE", "XinZhaoR"],
  },
  {
    id: "Yasuo",
    name: "Yasuo",
    spells: ["YasuoQ1Wrapper", "YasuoW", "YasuoE", "YasuoR"],
  },
  { id: "Yone", name: "Yone", spells: ["YoneQ", "YoneW", "YoneE", "YoneR"] },
  {
    id: "Yorick",
    name: "Yorick",
    spells: ["YorickQ", "YorickW", "YorickE", "YorickR"],
  },
  {
    id: "Yuumi",
    name: "Yuumi",
    spells: ["YuumiQ", "YuumiW", "YuumiE", "YuumiR"],
  },
  { id: "Zac", name: "Zac", spells: ["ZacQ", "ZacW", "ZacE", "ZacR"] },
  { id: "Zed", name: "Zed", spells: ["ZedQ", "ZedW", "ZedE", "ZedR"] },
  { id: "Zeri", name: "Zeri", spells: ["ZeriQ", "ZeriW", "ZeriE", "ZeriR"] },
  {
    id: "Ziggs",
    name: "Ziggs",
    spells: ["ZiggsQ", "ZiggsW", "ZiggsE", "ZiggsR"],
  },
  {
    id: "Zilean",
    name: "Zilean",
    spells: ["ZileanQ", "ZileanW", "TimeWarp", "ChronoShift"],
  },
  { id: "Zoe", name: "Zoe", spells: ["ZoeQ", "ZoeW", "ZoeE", "ZoeR"] },
  { id: "Zyra", name: "Zyra", spells: ["ZyraQ", "ZyraW", "ZyraE", "ZyraR"] },
];

export const lists = {
  spells: [
    "AatroxQ",
    "AatroxW",
    "AatroxE",
    "AatroxR",
    "AhriQ",
    "AhriW",
    "AhriE",
    "AhriR",
    "AkaliQ",
    "AkaliW",
    "AkaliE",
    "AkaliR",
    "AkshanQ",
    "AkshanW",
    "AkshanE",
    "AkshanR",
    "Pulverize",
    "Headbutt",
    "AlistarE",
    "FerociousHowl",
    "BandageToss",
    "AuraofDespair",
    "Tantrum",
    "CurseoftheSadMummy",
    "FlashFrost",
    "Crystallize",
    "Frostbite",
    "GlacialStorm",
    "AnnieQ",
    "AnnieW",
    "AnnieE",
    "AnnieR",
    "ApheliosQ_ClientTooltipWrapper",
    "ApheliosW",
    "ApheliosE_ClientTooltipWrapper",
    "ApheliosR",
    "AsheQ",
    "Volley",
    "AsheSpiritOfTheHawk",
    "EnchantedCrystalArrow",
    "AurelionSolQ",
    "AurelionSolW",
    "AurelionSolE",
    "AurelionSolR",
    "AzirQWrapper",
    "AzirW",
    "AzirEWrapper",
    "AzirR",
    "BardQ",
    "BardW",
    "BardE",
    "BardR",
    "BelvethQ",
    "BelvethW",
    "BelvethE",
    "BelvethR",
    "RocketGrab",
    "Overdrive",
    "PowerFist",
    "StaticField",
    "BrandQ",
    "BrandW",
    "BrandE",
    "BrandR",
    "BraumQ",
    "BraumW",
    "BraumE",
    "BraumRWrapper",
    "CaitlynQ",
    "CaitlynW",
    "CaitlynE",
    "CaitlynR",
    "CamilleQ",
    "CamilleW",
    "CamilleE",
    "CamilleR",
    "CassiopeiaQ",
    "CassiopeiaW",
    "CassiopeiaE",
    "CassiopeiaR",
    "Rupture",
    "FeralScream",
    "VorpalSpikes",
    "Feast",
    "PhosphorusBomb",
    "CarpetBomb",
    "GGun",
    "MissileBarrage",
    "DariusCleave",
    "DariusNoxianTacticsONH",
    "DariusAxeGrabCone",
    "DariusExecute",
    "DianaQ",
    "DianaOrbs",
    "DianaTeleport",
    "DianaR",
    "DravenSpinning",
    "DravenFury",
    "DravenDoubleShot",
    "DravenRCast",
    "DrMundoQ",
    "DrMundoW",
    "DrMundoE",
    "DrMundoR",
    "EkkoQ",
    "EkkoW",
    "EkkoE",
    "EkkoR",
    "EliseHumanQ",
    "EliseHumanW",
    "EliseHumanE",
    "EliseR",
    "EvelynnQ",
    "EvelynnW",
    "EvelynnE",
    "EvelynnR",
    "EzrealQ",
    "EzrealW",
    "EzrealE",
    "EzrealR",
    "FiddleSticksQ",
    "FiddleSticksW",
    "FiddleSticksE",
    "FiddleSticksR",
    "FioraQ",
    "FioraW",
    "FioraE",
    "FioraR",
    "FizzQ",
    "FizzW",
    "FizzE",
    "FizzR",
    "GalioQ",
    "GalioW",
    "GalioE",
    "GalioR",
    "GangplankQWrapper",
    "GangplankW",
    "GangplankE",
    "GangplankR",
    "GarenQ",
    "GarenW",
    "GarenE",
    "GarenR",
    "GnarQ",
    "GnarW",
    "GnarE",
    "GnarR",
    "GragasQ",
    "GragasW",
    "GragasE",
    "GragasR",
    "GravesQLineSpell",
    "GravesSmokeGrenade",
    "GravesMove",
    "GravesChargeShot",
    "GwenQ",
    "GwenW",
    "GwenE",
    "GwenR",
    "HecarimRapidSlash",
    "HecarimW",
    "HecarimRamp",
    "HecarimUlt",
    "HeimerdingerQ",
    "HeimerdingerW",
    "HeimerdingerE",
    "HeimerdingerR",
    "IllaoiQ",
    "IllaoiW",
    "IllaoiE",
    "IllaoiR",
    "IreliaQ",
    "IreliaW",
    "IreliaE",
    "IreliaR",
    "IvernQ",
    "IvernW",
    "IvernE",
    "IvernR",
    "HowlingGale",
    "SowTheWind",
    "EyeOfTheStorm",
    "ReapTheWhirlwind",
    "JarvanIVDragonStrike",
    "JarvanIVGoldenAegis",
    "JarvanIVDemacianStandard",
    "JarvanIVCataclysm",
    "JaxLeapStrike",
    "JaxEmpowerTwo",
    "JaxCounterStrike",
    "JaxRApexForm",
    "JayceToTheSkies",
    "JayceStaticField",
    "JayceThunderingBlow",
    "JayceStanceHtG",
    "JhinQ",
    "JhinW",
    "JhinE",
    "JhinR",
    "JinxQ",
    "JinxW",
    "JinxE",
    "JinxR",
    "KaisaQ",
    "KaisaW",
    "KaisaE",
    "KaisaR",
    "KalistaMysticShot",
    "KalistaW",
    "KalistaExpungeWrapper",
    "KalistaRx",
    "KarmaQ",
    "KarmaSpiritBind",
    "KarmaSolKimShield",
    "KarmaMantra",
    "KarthusLayWasteA1",
    "KarthusWallOfPain",
    "KarthusDefile",
    "KarthusFallenOne",
    "NullLance",
    "NetherBlade",
    "ForcePulse",
    "RiftWalk",
    "KatarinaQ",
    "KatarinaW",
    "KatarinaEWrapper",
    "KatarinaR",
    "KayleQ",
    "KayleW",
    "KayleE",
    "KayleR",
    "KaynQ",
    "KaynW",
    "KaynE",
    "KaynR",
    "KennenShurikenHurlMissile1",
    "KennenBringTheLight",
    "KennenLightningRush",
    "KennenShurikenStorm",
    "KhazixQ",
    "KhazixW",
    "KhazixE",
    "KhazixR",
    "KindredQ",
    "KindredW",
    "KindredEWrapper",
    "KindredR",
    "KledQ",
    "KledW",
    "KledE",
    "KledR",
    "KogMawQ",
    "KogMawBioArcaneBarrage",
    "KogMawVoidOoze",
    "KogMawLivingArtillery",
    "KSanteQ",
    "KSanteW",
    "KSanteE",
    "KSanteR",
    "LeblancQ",
    "LeblancW",
    "LeblancE",
    "LeblancR",
    "BlindMonkQOne",
    "BlindMonkWOne",
    "BlindMonkEOne",
    "BlindMonkRKick",
    "LeonaShieldOfDaybreak",
    "LeonaSolarBarrier",
    "LeonaZenithBlade",
    "LeonaSolarFlare",
    "LilliaQ",
    "LilliaW",
    "LilliaE",
    "LilliaR",
    "LissandraQ",
    "LissandraW",
    "LissandraE",
    "LissandraR",
    "LucianQ",
    "LucianW",
    "LucianE",
    "LucianR",
    "LuluQ",
    "LuluW",
    "LuluE",
    "LuluR",
    "LuxLightBinding",
    "LuxPrismaticWave",
    "LuxLightStrikeKugel",
    "LuxR",
    "SeismicShard",
    "Obduracy",
    "Landslide",
    "UFSlash",
    "MalzaharQ",
    "MalzaharW",
    "MalzaharE",
    "MalzaharR",
    "MaokaiQ",
    "MaokaiW",
    "MaokaiE",
    "MaokaiR",
    "AlphaStrike",
    "Meditate",
    "WujuStyle",
    "Highlander",
    "MissFortuneRicochetShot",
    "MissFortuneViciousStrikes",
    "MissFortuneScattershot",
    "MissFortuneBulletTime",
    "MonkeyKingDoubleAttack",
    "MonkeyKingDecoy",
    "MonkeyKingNimbus",
    "MonkeyKingSpinToWin",
    "MordekaiserQ",
    "MordekaiserW",
    "MordekaiserE",
    "MordekaiserR",
    "MorganaQ",
    "MorganaW",
    "MorganaE",
    "MorganaR",
    "NamiQ",
    "NamiW",
    "NamiE",
    "NamiR",
    "NasusQ",
    "NasusW",
    "NasusE",
    "NasusR",
    "NautilusAnchorDrag",
    "NautilusPiercingGaze",
    "NautilusSplashZone",
    "NautilusGrandLine",
    "NeekoQ",
    "NeekoW",
    "NeekoE",
    "NeekoR",
    "JavelinToss",
    "Bushwhack",
    "PrimalSurge",
    "AspectOfTheCougar",
    "NilahQ",
    "NilahW",
    "NilahE",
    "NilahR",
    "NocturneDuskbringer",
    "NocturneShroudofDarkness",
    "NocturneUnspeakableHorror",
    "NocturneParanoia",
    "NunuQ",
    "NunuW",
    "NunuE",
    "NunuR",
    "OlafAxeThrowCast",
    "OlafFrenziedStrikes",
    "OlafRecklessStrike",
    "OlafRagnarok",
    "OrianaIzunaCommand",
    "OrianaDissonanceCommand",
    "OrianaRedactCommand",
    "OrianaDetonateCommand",
    "OrnnQ",
    "OrnnW",
    "OrnnE",
    "OrnnR",
    "PantheonQ",
    "PantheonW",
    "PantheonE",
    "PantheonR",
    "PoppyQ",
    "PoppyW",
    "PoppyE",
    "PoppyR",
    "PykeQ",
    "PykeW",
    "PykeE",
    "PykeR",
    "QiyanaQ",
    "QiyanaW",
    "QiyanaE",
    "QiyanaR",
    "QuinnQ",
    "QuinnW",
    "QuinnE",
    "QuinnR",
    "RakanQ",
    "RakanW",
    "RakanE",
    "RakanR",
    "PowerBall",
    "DefensiveBallCurl",
    "PuncturingTaunt",
    "Tremors2",
    "RekSaiQ",
    "RekSaiW",
    "RekSaiE",
    "RekSaiRWrapper",
    "RellQ",
    "RellW_Dismount",
    "RellE",
    "RellR",
    "RenataQ",
    "RenataW",
    "RenataE",
    "RenataR",
    "RenektonCleave",
    "RenektonPreExecute",
    "RenektonSliceAndDice",
    "RenektonReignOfTheTyrant",
    "RengarQ",
    "RengarW",
    "RengarE",
    "RengarR",
    "RivenTriCleave",
    "RivenMartyr",
    "RivenFeint",
    "RivenFengShuiEngine",
    "RumbleFlameThrower",
    "RumbleShield",
    "RumbleGrenade",
    "RumbleCarpetBomb",
    "RyzeQWrapper",
    "RyzeW",
    "RyzeE",
    "RyzeR",
    "SamiraQ",
    "SamiraW",
    "SamiraE",
    "SamiraR",
    "SejuaniQ",
    "SejuaniW",
    "SejuaniE",
    "SejuaniR",
    "SennaQ",
    "SennaW",
    "SennaE",
    "SennaR",
    "SeraphineQ",
    "SeraphineW",
    "SeraphineE",
    "SeraphineR",
    "SettQ",
    "SettW",
    "SettE",
    "SettR",
    "Deceive",
    "JackInTheBox",
    "TwoShivPoison",
    "HallucinateFull",
    "ShenQ",
    "ShenW",
    "ShenE",
    "ShenR",
    "ShyvanaDoubleAttack",
    "ShyvanaImmolationAura",
    "ShyvanaFireball",
    "ShyvanaTransformCast",
    "PoisonTrail",
    "MegaAdhesive",
    "Fling",
    "InsanityPotion",
    "SionQ",
    "SionW",
    "SionE",
    "SionR",
    "SivirQ",
    "SivirW",
    "SivirE",
    "SivirR",
    "SkarnerVirulentSlash",
    "SkarnerExoskeleton",
    "SkarnerFracture",
    "SkarnerImpale",
    "SonaQ",
    "SonaW",
    "SonaE",
    "SonaR",
    "SorakaQ",
    "SorakaW",
    "SorakaE",
    "SorakaR",
    "SwainQ",
    "SwainW",
    "SwainE",
    "SwainR",
    "SylasQ",
    "SylasW",
    "SylasE",
    "SylasR",
    "SyndraQ",
    "SyndraW",
    "SyndraE",
    "SyndraR",
    "TahmKenchQ",
    "TahmKenchW",
    "TahmKenchE",
    "TahmKenchRWrapper",
    "TaliyahQ",
    "TaliyahWVC",
    "TaliyahE",
    "TaliyahR",
    "TalonQ",
    "TalonW",
    "TalonE",
    "TalonR",
    "TaricQ",
    "TaricW",
    "TaricE",
    "TaricR",
    "BlindingDart",
    "MoveQuick",
    "ToxicShot",
    "TeemoRCast",
    "ThreshQ",
    "ThreshW",
    "ThreshE",
    "ThreshRPenta",
    "TristanaQ",
    "TristanaW",
    "TristanaE",
    "TristanaR",
    "TrundleTrollSmash",
    "trundledesecrate",
    "TrundleCircle",
    "TrundlePain",
    "TryndamereQ",
    "TryndamereW",
    "TryndamereE",
    "UndyingRage",
    "WildCards",
    "PickACard",
    "CardmasterStack",
    "Destiny",
    "TwitchHideInShadows",
    "TwitchVenomCask",
    "TwitchExpunge",
    "TwitchFullAutomatic",
    "UdyrQ",
    "UdyrW",
    "UdyrE",
    "UdyrR",
    "UrgotQ",
    "UrgotW",
    "UrgotE",
    "UrgotR",
    "VarusQ",
    "VarusW",
    "VarusE",
    "VarusR",
    "VayneTumble",
    "VayneSilveredBolts",
    "VayneCondemn",
    "VayneInquisition",
    "VeigarBalefulStrike",
    "VeigarDarkMatter",
    "VeigarEventHorizon",
    "VeigarR",
    "VelkozQ",
    "VelkozW",
    "VelkozE",
    "VelkozR",
    "VexQ",
    "VexW",
    "VexE",
    "VexR",
    "ViQ",
    "ViW",
    "ViE",
    "ViR",
    "ViegoQ",
    "ViegoW",
    "ViegoE",
    "ViegoR",
    "ViktorPowerTransfer",
    "ViktorGravitonField",
    "ViktorDeathRay",
    "ViktorChaosStorm",
    "VladimirQ",
    "VladimirSanguinePool",
    "VladimirE",
    "VladimirHemoplague",
    "VolibearQ",
    "VolibearW",
    "VolibearE",
    "VolibearR",
    "WarwickQ",
    "WarwickW",
    "WarwickE",
    "WarwickR",
    "XayahQ",
    "XayahW",
    "XayahE",
    "XayahR",
    "XerathArcanopulseChargeUp",
    "XerathArcaneBarrage2",
    "XerathMageSpear",
    "XerathLocusOfPower2",
    "XinZhaoQ",
    "XinZhaoW",
    "XinZhaoE",
    "XinZhaoR",
    "YasuoQ1Wrapper",
    "YasuoW",
    "YasuoE",
    "YasuoR",
    "YoneQ",
    "YoneW",
    "YoneE",
    "YoneR",
    "YorickQ",
    "YorickW",
    "YorickE",
    "YorickR",
    "YuumiQ",
    "YuumiW",
    "YuumiE",
    "YuumiR",
    "ZacQ",
    "ZacW",
    "ZacE",
    "ZacR",
    "ZedQ",
    "ZedW",
    "ZedE",
    "ZedR",
    "ZeriQ",
    "ZeriW",
    "ZeriE",
    "ZeriR",
    "ZiggsQ",
    "ZiggsW",
    "ZiggsE",
    "ZiggsR",
    "ZileanQ",
    "ZileanW",
    "TimeWarp",
    "ChronoShift",
    "ZoeQ",
    "ZoeW",
    "ZoeE",
    "ZoeR",
    "ZyraQ",
    "ZyraW",
    "ZyraE",
    "ZyraR",
  ],
  champions: [
    "Aatrox",
    "Ahri",
    "Akali",
    "Akshan",
    "Alistar",
    "Amumu",
    "Anivia",
    "Annie",
    "Aphelios",
    "Ashe",
    "AurelionSol",
    "Azir",
    "Bard",
    "Belveth",
    "Blitzcrank",
    "Brand",
    "Braum",
    "Caitlyn",
    "Camille",
    "Cassiopeia",
    "Chogath",
    "Corki",
    "Darius",
    "Diana",
    "Draven",
    "DrMundo",
    "Ekko",
    "Elise",
    "Evelynn",
    "Ezreal",
    "Fiddlesticks",
    "Fiora",
    "Fizz",
    "Galio",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gragas",
    "Graves",
    "Gwen",
    "Hecarim",
    "Heimerdinger",
    "Illaoi",
    "Irelia",
    "Ivern",
    "Janna",
    "JarvanIV",
    "Jax",
    "Jayce",
    "Jhin",
    "Jinx",
    "Kaisa",
    "Kalista",
    "Karma",
    "Karthus",
    "Kassadin",
    "Katarina",
    "Kayle",
    "Kayn",
    "Kennen",
    "Khazix",
    "Kindred",
    "Kled",
    "KogMaw",
    "KSante",
    "Leblanc",
    "LeeSin",
    "Leona",
    "Lillia",
    "Lissandra",
    "Lucian",
    "Lulu",
    "Lux",
    "Malphite",
    "Malzahar",
    "Maokai",
    "MasterYi",
    "MissFortune",
    "MonkeyKing",
    "Mordekaiser",
    "Morgana",
    "Nami",
    "Nasus",
    "Nautilus",
    "Neeko",
    "Nidalee",
    "Nilah",
    "Nocturne",
    "Nunu",
    "Olaf",
    "Orianna",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Pyke",
    "Qiyana",
    "Quinn",
    "Rakan",
    "Rammus",
    "RekSai",
    "Rell",
    "Renata",
    "Renekton",
    "Rengar",
    "Riven",
    "Rumble",
    "Ryze",
    "Samira",
    "Sejuani",
    "Senna",
    "Seraphine",
    "Sett",
    "Shaco",
    "Shen",
    "Shyvana",
    "Singed",
    "Sion",
    "Sivir",
    "Skarner",
    "Sona",
    "Soraka",
    "Swain",
    "Sylas",
    "Syndra",
    "TahmKench",
    "Taliyah",
    "Talon",
    "Taric",
    "Teemo",
    "Thresh",
    "Tristana",
    "Trundle",
    "Tryndamere",
    "TwistedFate",
    "Twitch",
    "Udyr",
    "Urgot",
    "Varus",
    "Vayne",
    "Veigar",
    "Velkoz",
    "Vex",
    "Vi",
    "Viego",
    "Viktor",
    "Vladimir",
    "Volibear",
    "Warwick",
    "Xayah",
    "Xerath",
    "XinZhao",
    "Yasuo",
    "Yone",
    "Yorick",
    "Yuumi",
    "Zac",
    "Zed",
    "Zeri",
    "Ziggs",
    "Zilean",
    "Zoe",
    "Zyra",
  ],
};
